# Schema for the configuration files of the Simple Address module.

simpleaddress.settings:
  type: mapping
  label: 'SimpleAddress settings'
  mapping:
    default:
      type: sequence
      label: 'SimpleAddress fields allowed to be displayed'
      sequence:
        - type: string
          label: 'Content type'

